### ISSUE TITLE
Possible security issue: hard-coded password

### ISSUE THREAD

**Issue by akondasif** [limadelrey/spring-vs-quarkus#1]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of hard-coded passwords. According to [CWE](https://cwe.mitre.org/data/definitions/259.html), "A hard-coded password typically leads to a significant authentication failure that can be difficult for the system administrator to detect." 

Hopefully, you agree and will fix it.

Source: https://github.com/limadelrey/spring-vs-quarkus/blob/master/quarkus-rest-api/src/main/resources/application.properties and https://github.com/limadelrey/spring-vs-quarkus/blob/master/quarkus-reactive-rest-api/src/main/resources/application.properties and https://github.com/limadelrey/spring-vs-quarkus/blob/master/spring-rest-api/src/main/resources/application.properties

**Comment by limadelrey** [comment]
Hi @akondasif,

Thank you so much for pointing that out! To be honest I could be using system properties, environment variables or any other externalized configuration mechanism, but to be fair with you this repository just aims to show Quarkus key points concisely while comparing it to a traditional Spring application. Therefore, for its purpose, I would rather have simplicity over hiding password details. 

Hopefully you agree with me.

Have a nice one!

**Comment by akondasif** [comment]
@limadelrey 

Thanks for the feedback. As we go on and detect more instances of hard-coded secrets we will keep this in mind :)
